---
#- name: Verify
#  hosts: all
#  gather_facts: false
#  tasks:
#  - name: Example assertion
#    assert:
#      that: true
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure basic connectivity
      ping:

    - name: Include your role
      include_role:
        name: clickhouse

